package com.raillylinker.module_jpa.jpa_beans.db1_main.repositories;

import com.raillylinker.module_jpa.jpa_beans.db1_main.entities.Db1_RaillyLinkerCompany_TotalAuthJoinTheMembershipWithOauth2Verification;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface Db1_RaillyLinkerCompany_TotalAuthJoinTheMembershipWithOauth2Verification_Repository extends JpaRepository<Db1_RaillyLinkerCompany_TotalAuthJoinTheMembershipWithOauth2Verification, Long> {
}
