package com.raillylinker.module_jpa.jpa_beans.db1_main.repositories;

import com.raillylinker.module_jpa.jpa_beans.db1_main.entities.Db1_RaillyLinkerCompany_Service1JoinTheMembershipWithOauth2VerificationData;
import org.springframework.stereotype.Repository;


@Repository
public interface Db1_RaillyLinkerCompany_Service1JoinTheMembershipWithOauth2VerificationData_Repository extends JpaRepository<Db1_RaillyLinkerCompany_Service1JoinTheMembershipWithOauth2VerificationData, Long> {
}
